### ISSUE TITLE
Speed optimization without sacrificing quality.

### ISSUE THREAD

**Issue by tejasjohn** [insanely-elegant/elegantsite#1]
Hey Team,
Currently after optimizing Gifs/images we can solve the speed in loading time, But grains can be noticed in the gifs.
lets make a final on that and make a version that's quite balanced in both speed and quality of image.

cheers,  
Tejas

**Comment by akashpk97** [comment]
Hey Team,
I feel having grains in the gifs makes it a retro type feel to it.
